<?php

$config['rule_vendor'] = array(
    'name' => array('field'=>'name',
                    'label'=>'Name',
                    'rules'=>'required|xss_clean|min_length[3]'),
    'email' => array('field'=>'email',
                     'label'=>'Email',
                     'rules'=>'valid_email|is_unique[vendor\models\Vendor.email]'),
    'phone' => array('field'=>'phone',
                     'label'=>'Phone',
                     'rules'=>'required|valid_phone_number'),
    'fax' => array('field'=>'fax',
                   'label'=>'Fax',
                   'rules'=>'valid_phone_number'),
    'description' => array('field'=>'description',
                           'label'=>'Description',
                           'rules'=>'max_length[250]'),
    'order_frequency' => array('field'=>'order_frequency',
                               'label'=>'Order Frequency',
                               'rules'=>''),
    'shipping_address' => array('field'=>'shipping_address',
                                'label'=>'Shipping Address',
                                'rules'=>''),
    'shipping_city' => array('field'=>'shipping_city',
                             'label'=>'Shipping City',
                             'rules'=>''),
    'shipping_province_abbr' => array('field'=>'shipping_province_abbr',
                                      'label'=>'Shipping Province',
                                      'rules'=>''),
    'shipping_postal' => array('field'=>'shipping_postal',
                               'label'=>'Shipping Postal',
                               'rules'=>''),
    'billing_address' => array('field'=>'billing_address',
                               'label'=>'Billing Address',
                               'rules'=>''),
    'billing_city' => array('field'=>'billing_city',
                            'label'=>'Billing City',
                            'rules'=>''),
    'billing_province_abbr' => array('field'=>'billing_province_abbr',
                                     'label'=>'Billing Province',
                                     'rules'=>''),
    'billing_postal' => array('field'=>'billing_postal',
                              'label'=>'Billing Postal',
                              'rules'=>''),
    'hst_number' => array('field'=>'hst_number',
                          'label'=>'HST Number',
                          'rules'=>''),
    'bank_name' => array('field'=>'bank_name',
                         'label'=>'Bank Name',
                         'rules'=>''),
    'bank_branch' => array('field'=>'bank_branch',
                           'label'=>'Bank Branch',
                           'rules'=>''),
    'bank_account' => array('field'=>'bank_account',
                            'label'=>'Brank Account',
                            'rules'=>'')
);

$config['rule_customer'] = array(
    'name' => array('field'=>'name',
          'label'=>'Name',
          'rules'=>'required|xss_clean|min_length[3]'),
    'email' => array('field'=>'email',
          'label'=>'Email',
          'rules'=>'valid_email|is_unique[customer\models\Customer.email]'),
    'phone' => array('field'=>'phone',
          'label'=>'Phone',
          'rules'=>'required|valid_phone_number'),
    'fax' => array('field'=>'fax',
          'label'=>'Fax',
          'rules'=>'valid_phone_number'),
    'description' => array('field'=>'description',
          'label'=>'Description',
          'rules'=>'max_length[250]'),
    'shipping_address' => array('field'=>'shipping_address',
                                'label'=>'Shipping Address',
                                'rules'=>''),
    'shipping_city' => array('field'=>'shipping_city',
                             'label'=>'Shipping City',
                             'rules'=>''),
    'shipping_province_abbr' => array('field'=>'shipping_province_abbr',
                                      'label'=>'Shipping Province',
                                      'rules'=>''),
    'shipping_postal' => array('field'=>'shipping_postal',
                               'label'=>'Shipping Postal',
                               'rules'=>''),
    'billing_address' => array('field'=>'billing_address',
                               'label'=>'Billing Address',
                               'rules'=>''),
    'billing_city' => array('field'=>'billing_city',
                            'label'=>'Billing City',
                            'rules'=>''),
    'billing_province_abbr' => array('field'=>'billing_province_abbr',
                                     'label'=>'Billing Province',
                                     'rules'=>''),
    'billing_postal' => array('field'=>'billing_postal',
                              'label'=>'Billing Postal',
                              'rules'=>'')
);

$config['rule_product'] = array(
    'name' => array('field'=>'name',
          'label'=>'Name',
          'rules'=>'required|xss_clean|min_length[3]'),
    'barcode' => array('field'=>'barcode',
          'label'=>'Barcode',
          'rules'=>''),
    'SKU' => array('field'=>'SKU',
          'label'=>'SKU',
          'rules'=>''),
    'section' => array('field'=>'section',
          'label'=>'Section',
          'rules'=>''),
    'active' => array('field'=>'active',
          'label'=>'Active',
          'rules'=>'required'),
    'description' => array('field'=>'description',
          'label'=>'Description',
          'rules'=>''),
    'comment' => array('field'=>'comment',
          'label'=>'Comment',
          'rules'=>''),
    'cost' => array('field'=>'cost',
          'label'=>'Cost',
          'rules'=>'is_money'),
    'suggested_price' => array('field'=>'suggested_price',
          'label'=>'Suggested Retail Price',
          'rules'=>'is_money'),
    'no_service_price' => array('field'=>'no_service_price',
          'label'=>'No Service Price',
          'rules'=>'is_money'),
    'full_service_price' => array('field'=>'full_service_price',
          'label'=>'Full Service Price',
          'rules'=>'is_money'),
    'discount' => array('field'=>'discount',
          'label'=>'Discount',
          'rules'=>'is_money'),
    'CNC' => array('field'=>'CNC',
          'label'=>'CNC',
          'rules'=>'is_money'),
    'total_qty' => array('field'=>'total_qty',
          'label'=>'Total Qty',
          'rules'=>''),
    'qty_unit' => array('field'=>'qty_unit',
          'label'=>'Qty./Unit',
          'rules'=>''),
    'unit' => array('field'=>'unit',
          'label'=>'Unit',
          'rules'=>''),
    'unit_pack' => array('field' => 'unit_pack',
          'label' => 'Unit / Pack',
          'rules'=>''),
    'unit_case' => array('field' => 'unit_case',
          'label' => 'Unit / Case',
          'rules'=>''),
    'pack_case' => array('field' => 'pack_case',
          'label' => 'Pack / Case',
          'rules'=>''),
    'category' => array('field'=>'category',
          'label'=>'Category',
          'rules'=>'required'),
    'product_vendor' => array('field'=>'product_vendor',
          'label'=>'Vendor',
          'rules'=>'required')
);
