<?php

$config['rule_vendor'] = array(
    'name' => array('field'=>'name',
                    'label'=>'Name',
                    'rules'=>'required|xss_clean|min_length[3]'),
    'email' => array('field'=>'email',
                     'label'=>'Email',
                     'rules'=>'valid_email|is_unique[vendor\models\Vendor.email]'),
    'phone' => array('field'=>'phone',
                     'label'=>'Phone',
                     'rules'=>'required|valid_phone_number'),
    'fax' => array('field'=>'fax',
                   'label'=>'Fax',
                   'rules'=>'valid_phone_number'),
    'description' => array('field'=>'description',
                           'label'=>'Description',
                           'rules'=>'max_length[250]'),
    'order_frequency' => array('field'=>'order_frequency',
                               'label'=>'Order Frequency',
                               'rules'=>''),
    'shipping_address' => array('field'=>'shipping_address',
                                'label'=>'Shipping Address',
                                'rules'=>''),
    'shipping_city' => array('field'=>'shipping_city',
                             'label'=>'Shipping City',
                             'rules'=>''),
    'shipping_province_abbr' => array('field'=>'shipping_province_abbr',
                                      'label'=>'Shipping Province',
                                      'rules'=>''),
    'shipping_postal' => array('field'=>'shipping_postal',
                               'label'=>'Shipping Postal',
                               'rules'=>''),
    'billing_address' => array('field'=>'billing_address',
                               'label'=>'Billing Address',
                               'rules'=>''),
    'billing_city' => array('field'=>'billing_city',
                            'label'=>'Billing City',
                            'rules'=>''),
    'billing_province_abbr' => array('field'=>'billing_province_abbr',
                                     'label'=>'Billing Province',
                                     'rules'=>''),
    'billing_postal' => array('field'=>'billing_postal',
                              'label'=>'Billing Postal',
                              'rules'=>''),
    'hst_number' => array('field'=>'hst_number',
                          'label'=>'HST Number',
                          'rules'=>''),
    'bank_name' => array('field'=>'bank_name',
                         'label'=>'Bank Name',
                         'rules'=>''),
    'bank_branch' => array('field'=>'bank_branch',
                           'label'=>'Bank Branch',
                           'rules'=>''),
    'bank_account' => array('field'=>'bank_account',
                            'label'=>'Brank Account',
                            'rules'=>'')
);

$config['rule_customer'] = array(
    'name' => array('field'=>'name',
          'label'=>'Name',
          'rules'=>'required|xss_clean|min_length[3]'),
    'email' => array('field'=>'email',
          'label'=>'Email',
          'rules'=>'valid_email|is_unique[customer\models\Customer.email]'),
    'phone' => array('field'=>'phone',
          'label'=>'Phone',
          'rules'=>'required|valid_phone_number'),
    'fax' => array('field'=>'fax',
          'label'=>'Fax',
          'rules'=>'valid_phone_number'),
    'description' => array('field'=>'description',
          'label'=>'Description',
          'rules'=>'max_length[250]'),
    'shipping_address' => array('field'=>'shipping_address',
                                'label'=>'Shipping Address',
                                'rules'=>''),
    'shipping_city' => array('field'=>'shipping_city',
                             'label'=>'Shipping City',
                             'rules'=>''),
    'shipping_province_abbr' => array('field'=>'shipping_province_abbr',
                                      'label'=>'Shipping Province',
                                      'rules'=>''),
    'shipping_postal' => array('field'=>'shipping_postal',
                               'label'=>'Shipping Postal',
                               'rules'=>''),
    'billing_address' => array('field'=>'billing_address',
                               'label'=>'Billing Address',
                               'rules'=>''),
    'billing_city' => array('field'=>'billing_city',
                            'label'=>'Billing City',
                            'rules'=>''),
    'billing_province_abbr' => array('field'=>'billing_province_abbr',
                                     'label'=>'Billing Province',
                                     'rules'=>''),
    'billing_postal' => array('field'=>'billing_postal',
                              'label'=>'Billing Postal',
                              'rules'=>'')
);
